// $Id: OntologySearchEvent.as 2057 2011-03-30 01:12:31Z tom $
//
//  $Date: 2011-03-29 18:12:31 -0700 (Tue, 29 Mar 2011) $
//  $Revision: 2057 $
//
package edu.isi.bmkeg.ooevv.ontology {
	import flash.events.Event;
	
	import mx.collections.ArrayCollection;

	/** Class for events generated by using web services to
	 *  search for ontology terms.
	 * 
	 * @author University of Southern California
	 * @date $Date: 2011-03-29 18:12:31 -0700 (Tue, 29 Mar 2011) $
	 * @version $Revision: 2057 $
	 */
	public class OntologySearchEvent extends Event {
		public static const SEARCH_SERVICE_READY:String = "search-service-ready";
		public static const FIND_ONTOLOGY_TERMS:String = "find-ontology-terms";
		public static const LIST_ONTOLOGIES:String = "list-ontologies";
		public static const SET_ONTOLOGY_IDS:String = "set-ontology-ids";
		public static const ADD_ONTOLOGY_IDS:String = "add-ontology-ids";
		
		/**  The search results will be an ArrayCollection of matches from
		 *   particular type of search.  Each element of the collection will
		 *   be a generic ActionScript object with the following elements.
		 *   Not all of the elements will always be present or have values.
		 *   The ID value will always be there.
		 *   
		 *   TODO: This will change when we rationalize the interface to
		 *    the ontology and term search to use OntologyReference and 
		 *    OntologyTermReference objects instead of generic ActionScript.
		 *    That will mean changing the interaction with the search and
		 *    update functions.
		 *    For the meanwhile, we will use the basic forms as returned
		 *    by the NCBO service as our representation.
		 * 
		 *   SEARCH_SERVICE_READY: Dispatched when the search service is
		 *       ready to handle requests.  This allows certain search services
		 *       to have an asynchronous initialization process.  It will
		 *       be dispatched by all services when they are ready.  This can
		 *       happen immediately in the constructor if there is no delayed
		 *       initialization.
		 * 
		 *   LIST_ONTOLOGIES:
		 *      ontologyId: An ID for the ontology.  This may be a universal
		 *                    id or relative to the search engine.
		 *      displayName: The name of the ontology for display purposes
		 *      shortName: An abbreviated name for the ontology
		 *      description: A description of the ontology (long)
		 *      versionNumber: A version number for the ontology.      
		 * 
		 *   FIND_ONTOLOGY_TERMS:
		 * 
		 *      termId:  An ID for the term.  This may be a universal
		 *                    id or relative to the ontology.
		 *      shortName:  A short version of the ID.
		 *      displayName: The preferred human readable name for the term
		 *      description: A longer description or definition of the term
		 *      ontologyId: An ID for the ontology.  This may be a universal
		 *                    id or relative to the search engine.
		 *      ontologyDisplayName: Ontology name for display purposes.
		 * 
		 *   SET_ONTOLOGY_IDS: Events dispatched by the search dialog based
		 *   ADD_ONTOLOGY_IDS: on the action buttons chosen.  For setting
		 *                     the ID sets the ontologyIds to only the currently
		 *                     selected set, replacing existing Ids.  Adding
		 *                     the IDs adds to the existing set.
		 */
		public var searchResults:ArrayCollection;
		
		public function OntologySearchEvent(type:String, results:ArrayCollection) {
			super(type);
			this.searchResults = results;
		}		
	}
}