// $Id$
//
//  $Date$
//  $Revision$
//
package edu.isi.bmkeg.kefed.ontology {
	import flash.events.Event;
	
	import mx.collections.ArrayCollection;

	/** Class for events generated by using web services to
	 *  search for ontology terms.
	 * 
	 * @author University of Southern California
	 * @date $Date$
	 * @version $Revision$
	 */
	public class OntologySearchEvent extends Event {
		public static const FIND_ONTOLOGY_TERMS:String = "find-ontology-terms";
		public static const LIST_ONTOLOGIES:String = "list-ontologies";
		public static const SET_ONTOLOGY_IDS:String = "set-ontology-ids";
		public static const ADD_ONTOLOGY_IDS:String = "add-ontology-ids";
		
		public var searchResults:ArrayCollection;
		
		public function OntologySearchEvent(type:String, results:ArrayCollection) {
			super(type);
			this.searchResults = results;
		}		
	}
}